### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by elmot** [anthonyec/16seg#15]
Hello, I'd like to use some parts of this repo for my own project, but the repository has no license, and, thus, is [not open-source legally](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license).

Please add one (MIT for instance), that is only a couple of clicks.

**Comment by anthonyec** [comment]
[Done](https://github.com/anthonyec/16seg/blob/master/LICENSE)
